//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Behkap
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Запись визита.
    /// </summary>
    // *** Start programmer edit section *** (ЗаписьВизита CustomAttributes)

    // *** End programmer edit section *** (ЗаписьВизита CustomAttributes)
    [AutoAltered()]
    [Caption("Запись визита")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаписьВизитаE", new string[] {
            "записи as \'Записи\'",
            "услуги as \'Услуги\'",
            "визита as \'Визита\'",
            "сотрудника as \'Сотрудника\'",
            "Услуга as \'Услуга\'",
            "Услуга.Услуга as \'Услуга\'",
            "сотрудник as \'Сотрудник\'",
            "сотрудник.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "Услуга.Услуга",
            "сотрудник.ФИО"})]
    [MasterViewDefineAttribute("ЗаписьВизитаE", "Услуга", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Услуга")]
    [MasterViewDefineAttribute("ЗаписьВизитаE", "сотрудник", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    public class ЗаписьВизита : ICSSoft.STORMNET.DataObject
    {
        
        private int fзаписи;
        
        private int fуслуги;
        
        private int fвизита;
        
        private int fсотрудника;
        
        private IIS.Behkap.Услуга fУслуга;
        
        private IIS.Behkap.сотрудник fсотрудник;
        
        private IIS.Behkap.Визит fВизит;
        
        // *** Start programmer edit section *** (ЗаписьВизита CustomMembers)

        // *** End programmer edit section *** (ЗаписьВизита CustomMembers)

        
        /// <summary>
        /// визита.
        /// </summary>
        // *** Start programmer edit section *** (ЗаписьВизита.визита CustomAttributes)

        // *** End programmer edit section *** (ЗаписьВизита.визита CustomAttributes)
        public virtual int визита
        {
            get
            {
                // *** Start programmer edit section *** (ЗаписьВизита.визита Get start)

                // *** End programmer edit section *** (ЗаписьВизита.визита Get start)
                int result = this.fвизита;
                // *** Start programmer edit section *** (ЗаписьВизита.визита Get end)

                // *** End programmer edit section *** (ЗаписьВизита.визита Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаписьВизита.визита Set start)

                // *** End programmer edit section *** (ЗаписьВизита.визита Set start)
                this.fвизита = value;
                // *** Start programmer edit section *** (ЗаписьВизита.визита Set end)

                // *** End programmer edit section *** (ЗаписьВизита.визита Set end)
            }
        }
        
        /// <summary>
        /// записи.
        /// </summary>
        // *** Start programmer edit section *** (ЗаписьВизита.записи CustomAttributes)

        // *** End programmer edit section *** (ЗаписьВизита.записи CustomAttributes)
        public virtual int записи
        {
            get
            {
                // *** Start programmer edit section *** (ЗаписьВизита.записи Get start)

                // *** End programmer edit section *** (ЗаписьВизита.записи Get start)
                int result = this.fзаписи;
                // *** Start programmer edit section *** (ЗаписьВизита.записи Get end)

                // *** End programmer edit section *** (ЗаписьВизита.записи Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаписьВизита.записи Set start)

                // *** End programmer edit section *** (ЗаписьВизита.записи Set start)
                this.fзаписи = value;
                // *** Start programmer edit section *** (ЗаписьВизита.записи Set end)

                // *** End programmer edit section *** (ЗаписьВизита.записи Set end)
            }
        }
        
        /// <summary>
        /// сотрудника.
        /// </summary>
        // *** Start programmer edit section *** (ЗаписьВизита.сотрудника CustomAttributes)

        // *** End programmer edit section *** (ЗаписьВизита.сотрудника CustomAttributes)
        public virtual int сотрудника
        {
            get
            {
                // *** Start programmer edit section *** (ЗаписьВизита.сотрудника Get start)

                // *** End programmer edit section *** (ЗаписьВизита.сотрудника Get start)
                int result = this.fсотрудника;
                // *** Start programmer edit section *** (ЗаписьВизита.сотрудника Get end)

                // *** End programmer edit section *** (ЗаписьВизита.сотрудника Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаписьВизита.сотрудника Set start)

                // *** End programmer edit section *** (ЗаписьВизита.сотрудника Set start)
                this.fсотрудника = value;
                // *** Start programmer edit section *** (ЗаписьВизита.сотрудника Set end)

                // *** End programmer edit section *** (ЗаписьВизита.сотрудника Set end)
            }
        }
        
        /// <summary>
        /// услуги.
        /// </summary>
        // *** Start programmer edit section *** (ЗаписьВизита.услуги CustomAttributes)

        // *** End programmer edit section *** (ЗаписьВизита.услуги CustomAttributes)
        public virtual int услуги
        {
            get
            {
                // *** Start programmer edit section *** (ЗаписьВизита.услуги Get start)

                // *** End programmer edit section *** (ЗаписьВизита.услуги Get start)
                int result = this.fуслуги;
                // *** Start programmer edit section *** (ЗаписьВизита.услуги Get end)

                // *** End programmer edit section *** (ЗаписьВизита.услуги Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаписьВизита.услуги Set start)

                // *** End programmer edit section *** (ЗаписьВизита.услуги Set start)
                this.fуслуги = value;
                // *** Start programmer edit section *** (ЗаписьВизита.услуги Set end)

                // *** End programmer edit section *** (ЗаписьВизита.услуги Set end)
            }
        }
        
        /// <summary>
        /// Запись визита.
        /// </summary>
        // *** Start programmer edit section *** (ЗаписьВизита.сотрудник CustomAttributes)

        // *** End programmer edit section *** (ЗаписьВизита.сотрудник CustomAttributes)
        [PropertyStorage(new string[] {
                "сотрудник"})]
        [NotNull()]
        public virtual IIS.Behkap.сотрудник сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (ЗаписьВизита.сотрудник Get start)

                // *** End programmer edit section *** (ЗаписьВизита.сотрудник Get start)
                IIS.Behkap.сотрудник result = this.fсотрудник;
                // *** Start programmer edit section *** (ЗаписьВизита.сотрудник Get end)

                // *** End programmer edit section *** (ЗаписьВизита.сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаписьВизита.сотрудник Set start)

                // *** End programmer edit section *** (ЗаписьВизита.сотрудник Set start)
                this.fсотрудник = value;
                // *** Start programmer edit section *** (ЗаписьВизита.сотрудник Set end)

                // *** End programmer edit section *** (ЗаписьВизита.сотрудник Set end)
            }
        }
        
        /// <summary>
        /// Запись визита.
        /// </summary>
        // *** Start programmer edit section *** (ЗаписьВизита.Услуга CustomAttributes)

        // *** End programmer edit section *** (ЗаписьВизита.Услуга CustomAttributes)
        [PropertyStorage(new string[] {
                "Услуга"})]
        [NotNull()]
        public virtual IIS.Behkap.Услуга Услуга
        {
            get
            {
                // *** Start programmer edit section *** (ЗаписьВизита.Услуга Get start)

                // *** End programmer edit section *** (ЗаписьВизита.Услуга Get start)
                IIS.Behkap.Услуга result = this.fУслуга;
                // *** Start programmer edit section *** (ЗаписьВизита.Услуга Get end)

                // *** End programmer edit section *** (ЗаписьВизита.Услуга Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаписьВизита.Услуга Set start)

                // *** End programmer edit section *** (ЗаписьВизита.Услуга Set start)
                this.fУслуга = value;
                // *** Start programmer edit section *** (ЗаписьВизита.Услуга Set end)

                // *** End programmer edit section *** (ЗаписьВизита.Услуга Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Behkap.Визит.
        /// </summary>
        // *** Start programmer edit section *** (ЗаписьВизита.Визит CustomAttributes)

        // *** End programmer edit section *** (ЗаписьВизита.Визит CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Визит"})]
        public virtual IIS.Behkap.Визит Визит
        {
            get
            {
                // *** Start programmer edit section *** (ЗаписьВизита.Визит Get start)

                // *** End programmer edit section *** (ЗаписьВизита.Визит Get start)
                IIS.Behkap.Визит result = this.fВизит;
                // *** Start programmer edit section *** (ЗаписьВизита.Визит Get end)

                // *** End programmer edit section *** (ЗаписьВизита.Визит Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаписьВизита.Визит Set start)

                // *** End programmer edit section *** (ЗаписьВизита.Визит Set start)
                this.fВизит = value;
                // *** Start programmer edit section *** (ЗаписьВизита.Визит Set end)

                // *** End programmer edit section *** (ЗаписьВизита.Визит Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаписьВизитаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаписьВизитаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаписьВизитаE", typeof(IIS.Behkap.ЗаписьВизита));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ЗаписьВизита.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfЗаписьВизита CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfЗаписьВизита CustomAttributes)
    public class DetailArrayOfЗаписьВизита : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Behkap.DetailArrayOfЗаписьВизита members)

        // *** End programmer edit section *** (IIS.Behkap.DetailArrayOfЗаписьВизита members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ЗаписьВизита by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ЗаписьВизита.
        /// </summary>
        public DetailArrayOfЗаписьВизита(IIS.Behkap.Визит fВизит) : 
                base(typeof(ЗаписьВизита), ((ICSSoft.STORMNET.DataObject)(fВизит)))
        {
        }
        
        public IIS.Behkap.ЗаписьВизита this[int index]
        {
            get
            {
                return ((IIS.Behkap.ЗаписьВизита)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Behkap.ЗаписьВизита dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
