//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Behkap
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сотрудник.
    /// </summary>
    // *** Start programmer edit section *** (сотрудник CustomAttributes)

    // *** End programmer edit section *** (сотрудник CustomAttributes)
    [AutoAltered()]
    [Caption("Сотрудник")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("сотрудникE", new string[] {
            "ФИО as \'ФИО\'",
            "Должность as \'Должность\'",
            "с as \'С\'",
            "рож as \'Рож\'",
            "Пол as \'Пол\'",
            "Должности as \'Должности\'",
            "Должности.Должность as \'Должность\'"}, Hidden=new string[] {
            "Должности.Должность"})]
    [MasterViewDefineAttribute("сотрудникE", "Должности", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Должность")]
    [View("сотрудникL", new string[] {
            "ФИО as \'ФИО\'",
            "Должность as \'Должность\'",
            "с as \'С\'",
            "рож as \'Рож\'",
            "Пол as \'Пол\'",
            "Должности.Должность as \'Должность\'"})]
    public class сотрудник : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИО;
        
        private string fДолжность;
        
        private int fс;
        
        private System.DateTime fрож;
        
        private IIS.Behkap.Пол fПол;
        
        private IIS.Behkap.Должности fДолжности;
        
        // *** Start programmer edit section *** (сотрудник CustomMembers)

        // *** End programmer edit section *** (сотрудник CustomMembers)

        
        /// <summary>
        /// Должность.
        /// </summary>
        // *** Start programmer edit section *** (сотрудник.Должность CustomAttributes)

        // *** End programmer edit section *** (сотрудник.Должность CustomAttributes)
        [StrLen(255)]
        public virtual string Должность
        {
            get
            {
                // *** Start programmer edit section *** (сотрудник.Должность Get start)

                // *** End programmer edit section *** (сотрудник.Должность Get start)
                string result = this.fДолжность;
                // *** Start programmer edit section *** (сотрудник.Должность Get end)

                // *** End programmer edit section *** (сотрудник.Должность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (сотрудник.Должность Set start)

                // *** End programmer edit section *** (сотрудник.Должность Set start)
                this.fДолжность = value;
                // *** Start programmer edit section *** (сотрудник.Должность Set end)

                // *** End programmer edit section *** (сотрудник.Должность Set end)
            }
        }
        
        /// <summary>
        /// Пол.
        /// </summary>
        // *** Start programmer edit section *** (сотрудник.Пол CustomAttributes)

        // *** End programmer edit section *** (сотрудник.Пол CustomAttributes)
        public virtual IIS.Behkap.Пол Пол
        {
            get
            {
                // *** Start programmer edit section *** (сотрудник.Пол Get start)

                // *** End programmer edit section *** (сотрудник.Пол Get start)
                IIS.Behkap.Пол result = this.fПол;
                // *** Start programmer edit section *** (сотрудник.Пол Get end)

                // *** End programmer edit section *** (сотрудник.Пол Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (сотрудник.Пол Set start)

                // *** End programmer edit section *** (сотрудник.Пол Set start)
                this.fПол = value;
                // *** Start programmer edit section *** (сотрудник.Пол Set end)

                // *** End programmer edit section *** (сотрудник.Пол Set end)
            }
        }
        
        /// <summary>
        /// рож.
        /// </summary>
        // *** Start programmer edit section *** (сотрудник.рож CustomAttributes)

        // *** End programmer edit section *** (сотрудник.рож CustomAttributes)
        public virtual System.DateTime рож
        {
            get
            {
                // *** Start programmer edit section *** (сотрудник.рож Get start)

                // *** End programmer edit section *** (сотрудник.рож Get start)
                System.DateTime result = this.fрож;
                // *** Start programmer edit section *** (сотрудник.рож Get end)

                // *** End programmer edit section *** (сотрудник.рож Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (сотрудник.рож Set start)

                // *** End programmer edit section *** (сотрудник.рож Set start)
                this.fрож = value;
                // *** Start programmer edit section *** (сотрудник.рож Set end)

                // *** End programmer edit section *** (сотрудник.рож Set end)
            }
        }
        
        /// <summary>
        /// с.
        /// </summary>
        // *** Start programmer edit section *** (сотрудник.с CustomAttributes)

        // *** End programmer edit section *** (сотрудник.с CustomAttributes)
        public virtual int с
        {
            get
            {
                // *** Start programmer edit section *** (сотрудник.с Get start)

                // *** End programmer edit section *** (сотрудник.с Get start)
                int result = this.fс;
                // *** Start programmer edit section *** (сотрудник.с Get end)

                // *** End programmer edit section *** (сотрудник.с Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (сотрудник.с Set start)

                // *** End programmer edit section *** (сотрудник.с Set start)
                this.fс = value;
                // *** Start programmer edit section *** (сотрудник.с Set end)

                // *** End programmer edit section *** (сотрудник.с Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (сотрудник.ФИО CustomAttributes)

        // *** End programmer edit section *** (сотрудник.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (сотрудник.ФИО Get start)

                // *** End programmer edit section *** (сотрудник.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (сотрудник.ФИО Get end)

                // *** End programmer edit section *** (сотрудник.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (сотрудник.ФИО Set start)

                // *** End programmer edit section *** (сотрудник.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (сотрудник.ФИО Set end)

                // *** End programmer edit section *** (сотрудник.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Сотрудник.
        /// </summary>
        // *** Start programmer edit section *** (сотрудник.Должности CustomAttributes)

        // *** End programmer edit section *** (сотрудник.Должности CustomAttributes)
        [PropertyStorage(new string[] {
                "Должности"})]
        [NotNull()]
        public virtual IIS.Behkap.Должности Должности
        {
            get
            {
                // *** Start programmer edit section *** (сотрудник.Должности Get start)

                // *** End programmer edit section *** (сотрудник.Должности Get start)
                IIS.Behkap.Должности result = this.fДолжности;
                // *** Start programmer edit section *** (сотрудник.Должности Get end)

                // *** End programmer edit section *** (сотрудник.Должности Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (сотрудник.Должности Set start)

                // *** End programmer edit section *** (сотрудник.Должности Set start)
                this.fДолжности = value;
                // *** Start programmer edit section *** (сотрудник.Должности Set end)

                // *** End programmer edit section *** (сотрудник.Должности Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "сотрудникE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View сотрудникE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("сотрудникE", typeof(IIS.Behkap.сотрудник));
                }
            }
            
            /// <summary>
            /// "сотрудникL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View сотрудникL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("сотрудникL", typeof(IIS.Behkap.сотрудник));
                }
            }
        }
    }
}
