//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Behkap
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Состав услуги.
    /// </summary>
    // *** Start programmer edit section *** (СоставУслуги CustomAttributes)

    // *** End programmer edit section *** (СоставУслуги CustomAttributes)
    [AutoAltered()]
    [Caption("Состав услуги")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СоставУслугиE", new string[] {
            "услуги as \'Услуги\'",
            "товара as \'Товара\'",
            "табл as \'Табл\'",
            "Товар as \'Товар\'",
            "Товар.товара as \'Товара\'"}, Hidden=new string[] {
            "Товар.товара"})]
    [MasterViewDefineAttribute("СоставУслугиE", "Товар", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "товара")]
    public class СоставУслуги : ICSSoft.STORMNET.DataObject
    {
        
        private int fуслуги;
        
        private int fтовара;
        
        private int fтабл;
        
        private IIS.Behkap.Товар fТовар;
        
        private IIS.Behkap.Услуга fУслуга;
        
        // *** Start programmer edit section *** (СоставУслуги CustomMembers)

        // *** End programmer edit section *** (СоставУслуги CustomMembers)

        
        /// <summary>
        /// табл.
        /// </summary>
        // *** Start programmer edit section *** (СоставУслуги.табл CustomAttributes)

        // *** End programmer edit section *** (СоставУслуги.табл CustomAttributes)
        public virtual int табл
        {
            get
            {
                // *** Start programmer edit section *** (СоставУслуги.табл Get start)

                // *** End programmer edit section *** (СоставУслуги.табл Get start)
                int result = this.fтабл;
                // *** Start programmer edit section *** (СоставУслуги.табл Get end)

                // *** End programmer edit section *** (СоставУслуги.табл Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставУслуги.табл Set start)

                // *** End programmer edit section *** (СоставУслуги.табл Set start)
                this.fтабл = value;
                // *** Start programmer edit section *** (СоставУслуги.табл Set end)

                // *** End programmer edit section *** (СоставУслуги.табл Set end)
            }
        }
        
        /// <summary>
        /// товара.
        /// </summary>
        // *** Start programmer edit section *** (СоставУслуги.товара CustomAttributes)

        // *** End programmer edit section *** (СоставУслуги.товара CustomAttributes)
        public virtual int товара
        {
            get
            {
                // *** Start programmer edit section *** (СоставУслуги.товара Get start)

                // *** End programmer edit section *** (СоставУслуги.товара Get start)
                int result = this.fтовара;
                // *** Start programmer edit section *** (СоставУслуги.товара Get end)

                // *** End programmer edit section *** (СоставУслуги.товара Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставУслуги.товара Set start)

                // *** End programmer edit section *** (СоставУслуги.товара Set start)
                this.fтовара = value;
                // *** Start programmer edit section *** (СоставУслуги.товара Set end)

                // *** End programmer edit section *** (СоставУслуги.товара Set end)
            }
        }
        
        /// <summary>
        /// услуги.
        /// </summary>
        // *** Start programmer edit section *** (СоставУслуги.услуги CustomAttributes)

        // *** End programmer edit section *** (СоставУслуги.услуги CustomAttributes)
        public virtual int услуги
        {
            get
            {
                // *** Start programmer edit section *** (СоставУслуги.услуги Get start)

                // *** End programmer edit section *** (СоставУслуги.услуги Get start)
                int result = this.fуслуги;
                // *** Start programmer edit section *** (СоставУслуги.услуги Get end)

                // *** End programmer edit section *** (СоставУслуги.услуги Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставУслуги.услуги Set start)

                // *** End programmer edit section *** (СоставУслуги.услуги Set start)
                this.fуслуги = value;
                // *** Start programmer edit section *** (СоставУслуги.услуги Set end)

                // *** End programmer edit section *** (СоставУслуги.услуги Set end)
            }
        }
        
        /// <summary>
        /// Состав услуги.
        /// </summary>
        // *** Start programmer edit section *** (СоставУслуги.Товар CustomAttributes)

        // *** End programmer edit section *** (СоставУслуги.Товар CustomAttributes)
        [PropertyStorage(new string[] {
                "Товар"})]
        [NotNull()]
        public virtual IIS.Behkap.Товар Товар
        {
            get
            {
                // *** Start programmer edit section *** (СоставУслуги.Товар Get start)

                // *** End programmer edit section *** (СоставУслуги.Товар Get start)
                IIS.Behkap.Товар result = this.fТовар;
                // *** Start programmer edit section *** (СоставУслуги.Товар Get end)

                // *** End programmer edit section *** (СоставУслуги.Товар Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставУслуги.Товар Set start)

                // *** End programmer edit section *** (СоставУслуги.Товар Set start)
                this.fТовар = value;
                // *** Start programmer edit section *** (СоставУслуги.Товар Set end)

                // *** End programmer edit section *** (СоставУслуги.Товар Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Behkap.Услуга.
        /// </summary>
        // *** Start programmer edit section *** (СоставУслуги.Услуга CustomAttributes)

        // *** End programmer edit section *** (СоставУслуги.Услуга CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Услуга"})]
        public virtual IIS.Behkap.Услуга Услуга
        {
            get
            {
                // *** Start programmer edit section *** (СоставУслуги.Услуга Get start)

                // *** End programmer edit section *** (СоставУслуги.Услуга Get start)
                IIS.Behkap.Услуга result = this.fУслуга;
                // *** Start programmer edit section *** (СоставУслуги.Услуга Get end)

                // *** End programmer edit section *** (СоставУслуги.Услуга Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставУслуги.Услуга Set start)

                // *** End programmer edit section *** (СоставУслуги.Услуга Set start)
                this.fУслуга = value;
                // *** Start programmer edit section *** (СоставУслуги.Услуга Set end)

                // *** End programmer edit section *** (СоставУслуги.Услуга Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СоставУслугиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СоставУслугиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СоставУслугиE", typeof(IIS.Behkap.СоставУслуги));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of СоставУслуги.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfСоставУслуги CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfСоставУслуги CustomAttributes)
    public class DetailArrayOfСоставУслуги : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Behkap.DetailArrayOfСоставУслуги members)

        // *** End programmer edit section *** (IIS.Behkap.DetailArrayOfСоставУслуги members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type СоставУслуги by index.
        /// </summary>
        /// <summary>
        /// Adds object with type СоставУслуги.
        /// </summary>
        public DetailArrayOfСоставУслуги(IIS.Behkap.Услуга fУслуга) : 
                base(typeof(СоставУслуги), ((ICSSoft.STORMNET.DataObject)(fУслуга)))
        {
        }
        
        public IIS.Behkap.СоставУслуги this[int index]
        {
            get
            {
                return ((IIS.Behkap.СоставУслуги)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Behkap.СоставУслуги dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
